// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PontuaFlow.Data;

#nullable disable

namespace PontuaFlow.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260422232045_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PontuaFlow.Models.Dev", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Avatar")
                        .HasColumnType("text");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DataInicio")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Devs");
                });

            modelBuilder.Entity("PontuaFlow.Models.DevTeam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("DevTeams");
                });

            modelBuilder.Entity("PontuaFlow.Models.DevTeamMember", b =>
                {
                    b.Property<int>("DevId")
                        .HasColumnType("integer");

                    b.Property<int>("DevTeamId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("DevId", "DevTeamId");

                    b.HasIndex("DevTeamId");

                    b.ToTable("DevTeamMembers");
                });

            modelBuilder.Entity("PontuaFlow.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<string>("Foto")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("PontuaFlow.Models.Task", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DataFim")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataInicio")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<int>("DevId")
                        .HasColumnType("integer");

                    b.Property<string>("NomeTarefa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Pontuacao")
                        .HasColumnType("integer");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<int>("WeekId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DevId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("WeekId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("PontuaFlow.Models.TaskTeamAssignment", b =>
                {
                    b.Property<int>("TaskId")
                        .HasColumnType("integer");

                    b.Property<int>("DevTeamId")
                        .HasColumnType("integer");

                    b.HasKey("TaskId", "DevTeamId");

                    b.HasIndex("DevTeamId");

                    b.ToTable("TaskTeamAssignments");
                });

            modelBuilder.Entity("PontuaFlow.Models.Week", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DataFim")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataInicio")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NumeroSemana")
                        .HasColumnType("integer");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "NumeroSemana")
                        .IsUnique();

                    b.ToTable("Weeks");
                });

            modelBuilder.Entity("PontuaFlow.Models.Dev", b =>
                {
                    b.HasOne("PontuaFlow.Models.Project", "Project")
                        .WithMany("Devs")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PontuaFlow.Models.DevTeam", b =>
                {
                    b.HasOne("PontuaFlow.Models.Project", "Project")
                        .WithMany("DevTeams")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PontuaFlow.Models.DevTeamMember", b =>
                {
                    b.HasOne("PontuaFlow.Models.Dev", "Dev")
                        .WithMany("DevTeamMembers")
                        .HasForeignKey("DevId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PontuaFlow.Models.DevTeam", "DevTeam")
                        .WithMany("DevTeamMembers")
                        .HasForeignKey("DevTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dev");

                    b.Navigation("DevTeam");
                });

            modelBuilder.Entity("PontuaFlow.Models.Task", b =>
                {
                    b.HasOne("PontuaFlow.Models.Dev", "Dev")
                        .WithMany("Tasks")
                        .HasForeignKey("DevId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PontuaFlow.Models.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PontuaFlow.Models.Week", "Week")
                        .WithMany("Tasks")
                        .HasForeignKey("WeekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dev");

                    b.Navigation("Project");

                    b.Navigation("Week");
                });

            modelBuilder.Entity("PontuaFlow.Models.TaskTeamAssignment", b =>
                {
                    b.HasOne("PontuaFlow.Models.DevTeam", "DevTeam")
                        .WithMany("TaskTeamAssignments")
                        .HasForeignKey("DevTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PontuaFlow.Models.Task", "Task")
                        .WithMany("TaskTeamAssignments")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DevTeam");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("PontuaFlow.Models.Week", b =>
                {
                    b.HasOne("PontuaFlow.Models.Project", "Project")
                        .WithMany("Weeks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PontuaFlow.Models.Dev", b =>
                {
                    b.Navigation("DevTeamMembers");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("PontuaFlow.Models.DevTeam", b =>
                {
                    b.Navigation("DevTeamMembers");

                    b.Navigation("TaskTeamAssignments");
                });

            modelBuilder.Entity("PontuaFlow.Models.Project", b =>
                {
                    b.Navigation("DevTeams");

                    b.Navigation("Devs");

                    b.Navigation("Tasks");

                    b.Navigation("Weeks");
                });

            modelBuilder.Entity("PontuaFlow.Models.Task", b =>
                {
                    b.Navigation("TaskTeamAssignments");
                });

            modelBuilder.Entity("PontuaFlow.Models.Week", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
